package com.company.aidev.workflow;

import com.company.aidev.config.JiraProperties;
import com.company.aidev.domain.AcceptanceReport;
import com.company.aidev.domain.CodeReview;
import com.company.aidev.domain.SecurityReport;
import com.company.aidev.domain.TechnicalPlan;
import com.company.aidev.domain.TestReport;
import com.company.aidev.domain.TicketAnalysis;
import com.company.aidev.persistence.entity.WorkflowEntity;
import java.util.List;
import org.springframework.stereotype.Component;

/**
 * Builds the merge request title, description and final report.
 *
 * <p>The description is written for the human reviewer who arrives with no context: what was asked,
 * what changed, what was verified, and — importantly — what the agents could not verify.
 */
@Component
public class MergeRequestReportBuilder {

    private static final String SIGNATURE = "Generated by:\nAI Dev Platform";

    private final JiraProperties jiraProperties;

    public MergeRequestReportBuilder(JiraProperties jiraProperties) {
        this.jiraProperties = jiraProperties;
    }

    public String title(TicketAnalysis analysis) {
        return analysis.ticketId() + " " + shortObjective(analysis.objective());
    }

    public String commitMessage(TicketAnalysis analysis) {
        return analysis.ticketId() + " " + shortObjective(analysis.objective());
    }

    /** Description posted when the merge request is created, before the reviews have run. */
    public String initialDescription(
            WorkflowEntity workflow, TicketAnalysis analysis, TechnicalPlan plan, TestReport testReport) {

        StringBuilder sb = new StringBuilder();
        appendSource(sb, workflow, analysis, "\n");
        sb.append("Objective:\n").append(analysis.objective()).append("\n\n");

        sb.append("Changes:\n");
        if (plan.filesToModify().isEmpty()) {
            sb.append("- see the diff\n");
        } else {
            plan.filesToModify()
                    .forEach(file -> sb.append("- ")
                            .append(file.changeType())
                            .append(' ')
                            .append(file.path())
                            .append(" — ")
                            .append(file.reason())
                            .append('\n'));
        }

        sb.append("\nTests:\n");
        sb.append("- ")
                .append(testReport.totalTests() - testReport.failedTests())
                .append('/')
                .append(testReport.totalTests())
                .append(" passing locally\n");
        plan.testsToAdd().forEach(test -> sb.append("- ").append(test).append('\n'));

        sb.append("\nAI Review:\nPENDING\n");
        sb.append("\nSecurity:\nPENDING\n");
        sb.append("\nAcceptance:\nPENDING\n");
        sb.append("\nWorkflow:\n").append(workflow.getId()).append('\n');
        sb.append("\n").append(SIGNATURE).append('\n');
        sb.append("\n> Automatic merge is disabled. A human must review and merge this change.\n");
        return sb.toString();
    }

    /** Full report posted as a merge request comment once every agent has run. */
    public String finalReport(
            WorkflowEntity workflow,
            TicketAnalysis analysis,
            TestReport testReport,
            CodeReview codeReview,
            SecurityReport securityReport,
            AcceptanceReport acceptanceReport) {

        StringBuilder sb = new StringBuilder();
        sb.append("## AI Dev Platform report\n\n");
        if (workflow.isJiraBacked()) {
            sb.append("Jira: ").append(jiraLink(analysis.ticketId())).append("  \n");
        } else {
            sb.append("Direct request: `").append(analysis.ticketId()).append("`  \n");
        }
        sb.append("Workflow: `").append(workflow.getId()).append("`  \n");
        sb.append("Development attempts: ").append(workflow.getDevelopmentAttempts()).append("\n\n");

        sb.append("| Gate | Result |\n|---|---|\n");
        sb.append("| Local tests | ")
                .append(testReport.successful() ? "PASS" : "FAIL")
                .append(" (")
                .append(testReport.totalTests() - testReport.failedTests())
                .append('/')
                .append(testReport.totalTests())
                .append(") |\n");
        sb.append("| Code review | ").append(codeReview == null ? "n/a" : codeReview.decision()).append(" |\n");
        sb.append("| Security review | ").append(securityReport == null ? "n/a" : securityReport.decision()).append(" |\n");
        sb.append("| Acceptance | ")
                .append(acceptanceReport == null
                        ? "n/a"
                        : acceptanceReport.passedCriteria() + "/" + acceptanceReport.totalCriteria())
                .append(" |\n\n");

        if (acceptanceReport != null && !acceptanceReport.results().isEmpty()) {
            sb.append("### Acceptance criteria\n\n");
            int index = 1;
            for (var result : acceptanceReport.results()) {
                sb.append("**AC").append(index++).append("** — ").append(result.criterion()).append("  \n");
                sb.append("Status: `").append(result.status()).append("`  \n");
                if (!result.evidence().isEmpty()) {
                    sb.append("Evidence:\n");
                    result.evidence().forEach(evidence -> sb.append("- ").append(evidence).append('\n'));
                }
                if (result.comment() != null && !result.comment().isBlank()) {
                    sb.append("_").append(result.comment()).append("_\n");
                }
                sb.append('\n');
            }
        }

        appendFindings(sb, "Code review findings", codeReview);
        appendSecurityFindings(sb, securityReport);

        if (!testReport.missingTestCases().isEmpty()) {
            sb.append("### Coverage gaps still open\n\n");
            testReport.missingTestCases().forEach(gap -> sb.append("- ").append(gap).append('\n'));
            sb.append('\n');
        }

        sb.append("---\n");
        sb.append("_Automatic merge is disabled. This change was written and reviewed by LLM agents; "
                + "a human reviewer remains responsible for what is merged._\n");
        return sb.toString();
    }

    /** Updated description reflecting the final gate results. */
    public String finalDescription(
            String initialDescription,
            CodeReview codeReview,
            SecurityReport securityReport,
            AcceptanceReport acceptanceReport) {

        String result = initialDescription;
        result = result.replace(
                "AI Review:\nPENDING", "AI Review:\n" + (codeReview == null ? "n/a" : codeReview.decision().name()));
        result = result.replace(
                "Security:\nPENDING",
                "Security:\n" + (securityReport == null ? "n/a" : securityReport.decision().name()));
        result = result.replace(
                "Acceptance:\nPENDING",
                "Acceptance:\n"
                        + (acceptanceReport == null
                                ? "n/a"
                                : acceptanceReport.passedCriteria() + "/" + acceptanceReport.totalCriteria()));
        return result;
    }

    private static void appendFindings(StringBuilder sb, String title, CodeReview review) {
        if (review == null || review.findings().isEmpty()) {
            return;
        }
        sb.append("### ").append(title).append("\n\n");
        review.findings().forEach(finding -> sb.append(finding.toMarkdown()).append('\n'));
        sb.append('\n');
    }

    private static void appendSecurityFindings(StringBuilder sb, SecurityReport report) {
        if (report == null || report.findings().isEmpty()) {
            return;
        }
        sb.append("### Security findings\n\n");
        report.findings().forEach(finding -> sb.append(finding.toMarkdown()).append('\n'));
        sb.append('\n');
    }

    private String jiraLink(String ticketId) {
        String base = jiraProperties.baseUrl();
        String normalized = base.endsWith("/") ? base.substring(0, base.length() - 1) : base;
        return "[" + ticketId + "](" + normalized + "/browse/" + ticketId + ")";
    }

    private void appendSource(StringBuilder sb, WorkflowEntity workflow, TicketAnalysis analysis, String suffix) {
        if (workflow.isJiraBacked()) {
            sb.append("Jira:\n").append(jiraLink(analysis.ticketId())).append(suffix);
        } else {
            sb.append("Direct request:\n").append(workflow.getSourceMessage()).append(suffix);
        }
    }

    private static String shortObjective(String objective) {
        if (objective == null || objective.isBlank()) {
            return "automated change";
        }
        String oneLine = objective.replaceAll("\\s+", " ").trim();
        String withoutTrailingDot = oneLine.endsWith(".") ? oneLine.substring(0, oneLine.length() - 1) : oneLine;
        return withoutTrailingDot.length() <= 120 ? withoutTrailingDot : withoutTrailingDot.substring(0, 117) + "...";
    }

    /** Labels applied to every merge request the platform opens. */
    public List<String> labels(String configuredLabel) {
        return List.of(configuredLabel);
    }
}
